version: "3.9"
services:
  redis:
    image: redislabs/redismod:latest
    restart: always
    ports:
      - 6379:6379
    # mirrors this https://github.com/RedisLabsModules/redismod/blob/master/Dockerfile, update the entry should there be any changes
    entrypoint: >
      redis-server
        /usr/local/etc/redis/redis.conf
        --loadmodule /usr/lib/redis/modules/redisai.so
        --loadmodule /usr/lib/redis/modules/redisearch.so
        --loadmodule /usr/lib/redis/modules/redisgraph.so
        --loadmodule /usr/lib/redis/modules/redistimeseries.so
        --loadmodule /usr/lib/redis/modules/rejson.so
        --loadmodule /usr/lib/redis/modules/redisbloom.so
        --loadmodule /usr/lib/redis/modules/redisgears.so
        Plugin /var/opt/redislabs/modules/rg/plugin/gears_python.so
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
